### ISSUE TITLE
Your example have bugs

### ISSUE THREAD

**Issue by flaviobarros** [jb-1980/khan_api_wrapper#2]
Firstly thank you! You have solved a big issue for me with this library! I was trying to use it now and I detected some mistakes in the example documentation. In the example you have used

`token, secret = kauth.authenticate_self()`

but looking at your code the correct is

`token, secret = kauth.authorize_self()`

Where you use 

`kapi = KhanApi(consumer_key, consumer_token, token, secret)`

the correct is

`kapi = KhanAPI(consumer_key, consumer_token, token, secret)`

**Comment by jb-1980** [comment]
Thanks for picking this up. I have merged your pull request to update.
